#!/usr/bin/env bash

action=$1
ROOT=$(pwd)
LOGPATH=${ROOT}/storage/logs

function do_start()
{
    get_pid
    if [ "$pid" ] ;then
       echo "already started"
    else
        echo start it
        nohup php ${ROOT}/artisan queue:work --daemon --queue=default --sleep=1 --tries=2 >> ${LOGPATH}/queue_default.log 2>&1 &
        echo $(date +%Y-%m-%di_%H:%M:%S)"restarted" >> ${LOGPATH}/queue.log
    fi
}

function do_stop()
{
    get_pid
    if [ "$pid" ] ;then
       kill -15 $pid
       echo "stopped the process"
    else
       echo "no process is running"
    fi
}

function get_pid()
{
   pid=`ps -fe | grep "${ROOT}" | grep "queue=default" | grep -v "grep" |awk -F " " '{print $2}'`
}


case $action in

start)
    do_start;
;;

stop)
    do_stop;
;;

restart)
    do_stop;
    do_start;
;;

info)
    get_pid;
    if [ "$pid" ] ;then
       echo "the process pid is "$pid
    else
       echo "no process is running"
    fi
;;
*)
    echo "bad args, you need input args in start,stop,restart"
;;

esac
